### ISSUE TITLE
Coriolis Parameter value in LES_driven_SCM

### ISSUE THREAD

**Issue by yairchn** [CliMA/TurbulenceConvection.jl#1160]
It seems that we are suing the [Coriolis parameter value](https://github.com/CliMA/TurbulenceConvection.jl/blob/f541aa4b1c689a24e8db2249bee1164413a46031/driver/Cases.jl#L1169) from Bomex in all `LES_driven_SCM` cases as default. It is not clear to me if the LES uses Coriolis, but if it so, it is probably changing with the latitude of the GCM column.

**Comment by yairchn** [comment]
PR #1159 will move the value of Coriolis parameter to the namelist and we should followup with a PR that reads it from the LES (or GCM) inputs

**Comment by haakon-e** [comment]
It appears we are doing it right for Rico:
https://github.com/CliMA/TurbulenceConvection.jl/blob/f541aa4b1c689a24e8db2249bee1164413a46031/driver/Cases.jl#L501-L509

**Comment by szy21** [comment]
The GCM-driven LES cases didn't use Coriolis.

**Comment by yairchn** [comment]
> The GCM-driven LES cases didn't use Coriolis.

in that case its an easy fix in #1159 I will just set it to zero

**Comment by yairchn** [comment]
sorry the flag was set to false  - my mistake 
https://github.com/CliMA/TurbulenceConvection.jl/blob/f541aa4b1c689a24e8db2249bee1164413a46031/driver/Cases.jl#L1169
