### ISSUE TITLE
Differences between EOS and PhaseEquil_pθq for similar inputs

### ISSUE THREAD

**Issue by yairchn** [CliMA/TurbulenceConvection.jl#144]
If you run any case on this branch '[ckajyc/thermo](https://github.com/CliMA/TurbulenceConvection.jl/tree/ckajyc/thermo)' it will print the temperature difference between 'PhaseEquil_pθq' and 'eos' calculations. This difference is not small (order of 0.5K) and might be part of the reason 'ckaj/thermo' produces large updraft fractions

**Comment by yairchn** [comment]
The branch itself is an attempt to merge 'ckaj/thermo' that does not work with 'yc/redo_thermo3' that is working - while keeping the 'yc/redo_thermo3'  version in most conflicts but for eos function.

**Comment by charleskawczynski** [comment]
Closed by #325
