### ISSUE TITLE
Should we revert #332?

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/TurbulenceConvection.jl#337]
I just realized that #332 actually results in bad `HVar` in DYCOMS (and likely other cases). It merged without requiring to update the mse tables because, I believe, we don't test certain second order moments. If this is important to retain then I'm fine with reverting it, but I'm also wondering if we should be testing these second order moments in simulations if it is important.

cc @yairchn, @ilopezgp, @trontrytel

**Comment by ilopezgp** [comment]
Yikes! Yes, let's revert this. We should add tests for `Hvar` and `Qtvar`, those are important fields.

**Comment by charleskawczynski** [comment]
Closed by #338
