### ISSUE TITLE
NCDatasets allocations

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/TurbulenceConvection.jl#723]
Right now, our maximum allocations are coming from NCDatasets (in [this release](https://github.com/Alexander-Barth/NCDatasets.jl/blob/ab926ebbadcb14786ec2feb0d1fd4ba2e5f918ae/src/))

<img width="600" alt="Screen Shot 2022-01-10 at 12 12 06 PM" src="https://user-images.githubusercontent.com/1880641/148832634-f3d59ce4-d357-4c24-95fe-d7a2dcdeb635.png">

The top two points are:
 - [here (in `nc_inq_var`)](https://github.com/Alexander-Barth/NCDatasets.jl/blob/ab926ebbadcb14786ec2feb0d1fd4ba2e5f918ae/src/netcdf_c.jl#L1336)
 - [here (in `nc_inq_varname`)](https://github.com/Alexander-Barth/NCDatasets.jl/blob/ab926ebbadcb14786ec2feb0d1fd4ba2e5f918ae/src/netcdf_c.jl#L1383)
 - [here (in `setindex!`)](https://github.com/Alexander-Barth/NCDatasets.jl/blob/ab926ebbadcb14786ec2feb0d1fd4ba2e5f918ae/src/cfvariable.jl#L626)
 - [here (in `nc_inq_var`)](https://github.com/Alexander-Barth/NCDatasets.jl/blob/ab926ebbadcb14786ec2feb0d1fd4ba2e5f918ae/src/netcdf_c.jl#L1337)

The 3rd one looks like something we can't really improve on, but the 1st, 2nd and 4th ones look like they potentially could. @Alexander-Barth, could these `zeros` arrays be pre-allocated?

**Comment by Alexander-Barth** [comment]
I am not sure why you have so many call to `nc_inq_var` / `nc_inq_varname`. Are you closing/opening the file in a (hot) loop? Can you show me where in your code you are saving the data into a NetCDF file?

**Comment by Alexander-Barth** [comment]
Do these changes have an impact on your benchmark?
https://github.com/Alexander-Barth/NCDatasets.jl/commit/2747a78377e38316e4660306853418ded4605965

**Comment by charleskawczynski** [comment]
> I am not sure why you have so many call to `nc_inq_var` / `nc_inq_varname`. Are you closing/opening the file in a (hot) loop? Can you show me where in your code you are saving the data into a NetCDF file?

Yeah, I'm not sure, I'll have to look a bit closer. Could it be related to having many variables, somehow? I should have some time to find out who's calling these methods sometime this or next week.

> I will also look on my side, if if I can replace `nc_inq_var` by some more specific functions (as the variable name is not always needed).

That sounds great, thanks!

> Do these changes have an impact on your benchmark? https://github.com/Alexander-Barth/NCDatasets.jl/commit/2747a78377e38316e4660306853418ded4605965

Awesome, I can easily try this out now, thanks! I'll post the benchmark with this commit once it finishes.

**Comment by charleskawczynski** [comment]
Here's the updated allocations plot with https://github.com/Alexander-Barth/NCDatasets.jl/commit/2747a78377e38316e4660306853418ded4605965:

<img width="700" alt="Screen Shot 2022-01-11 at 10 40 29 AM" src="https://user-images.githubusercontent.com/1880641/149002403-d15f6b90-4dc4-4b58-95c3-2dfcb1e678fa.png">

So, it looks better (one of the points seems to be gone)!

**Comment by Alexander-Barth** [comment]
> Yeah, I'm not sure, I'll have to look a bit closer. Could it be related to having many variables, somehow? I should have some time to find out who's calling these methods sometime this or next week.

Yes, this can be related to this.
https://github.com/Alexander-Barth/NCDatasets.jl/issues/135#issuecomment-883179369

If you can find out wheter you are opening/closing the file in a loop that would help.

For your information, I made some small optimization in the master version to reduce the allocation further (avoid getting the name of a variable or attribute when I can work with the numeric ids). Do they reduce the allocations for your use case a bit more?

**Comment by charleskawczynski** [comment]
> Yes, this can be related to this. [Alexander-Barth/NCDatasets.jl#135 (comment)](https://github.com/Alexander-Barth/NCDatasets.jl/issues/135#issuecomment-883179369)

Ahh, ok, makes sense.

> If you can find out wheter you are opening/closing the file in a loop that would help.

I looked and, actually, it seems that we're only opening/closing nc files twice per run: 1) open-close once after initialization, and 2) open before running, and close after running. So, I'm now wondering if this is all just related to [Alexander-Barth/NCDatasets.jl#135 (comment)](https://github.com/Alexander-Barth/NCDatasets.jl/issues/135#issuecomment-883179369)

> For your information, I made some small optimization in the master version to reduce the allocation further (avoid getting the name of a variable or attribute when I can work with the numeric ids). Do they reduce the allocations for your use case a bit more?

Nice, thanks again for looking into this! I'll give it a try in that same branch and re-report.

**Comment by charleskawczynski** [comment]
It looks like what's in master improves things for the most part. I don't know that I'd expect that we'd be able to reduce allocations further with `src/cfvariable.jl`, since I think that corresponds to the `setindex!`ing of data to disc. One `src/netcdf_c.jl` allocation site is still there, but it looks like it's right in there with allocations in other packages, including our own. Overall, this is great, thanks for updating things so quickly, @Alexander-Barth! We look forward to the next release! 😄

<img width="1494" alt="Screen Shot 2022-01-12 at 4 31 12 PM" src="https://user-images.githubusercontent.com/1880641/149245123-7acbf08b-2850-4ec8-909f-53708a1faf2a.png">

**Comment by Alexander-Barth** [comment]
This is great to hear! 

The allocations in `setindex!` are due the fact that the data might need to be scaled (using scale_factor, add_offset, time unit transformation) or their type need to be transformed (computation in Float64 but saving in Float32 for example). Do you use any of these transformation? If not it might be possible to pass the array with the results directly to the NetCDF library by specializing for this case.

**Comment by charleskawczynski** [comment]
Oh, nice! We aren't doing any transformations, as far as I know. [This line](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/NetCDFIO.jl#L144) is the hot spot of where we write to file, and [this block](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/NetCDFIO.jl#L141-L176) includes some others, but they're significantly less.

How can we use this new `CFtransformdata`? Should I just retry on the latest master branch? Or do we need to update the broadcasted assignments on our end?

**Comment by Alexander-Barth** [comment]
Yes, updating to the new master branch should be sufficient 😀

I made a special case, when all storage attributes are nothing. So this:

```julia
 @show self.vars[group][var_name]._storage_attrib
```
should return:
```
(fillvalue = nothing, scale_factor = nothing, add_offset = nothing, calendar = nothing, time_origin = nothing, time_factor = nothing)
```

for hitting this optimized case. Also the type should be exactly the same as in the NetCDF files (e.g. Float64 or computation in NC_DOUBLE in the NetCDF file). Union{Float64,Missing} for computation for example and NC_DOUBLE for stage would still require copying as I don't think there is a way to convert an array of Union{Float64,Missing} to an array of Float64 without copying.

**Comment by charleskawczynski** [comment]
I can confirm that `@show self.vars[group][var_name]._storage_attrib` returns `(fillvalue = nothing, scale_factor = nothing, add_offset = nothing, calendar = nothing, time_origin = nothing, time_factor = nothing)`. @Alexander-Barth, is there a plan for a new NCDatasets release?

We've switched from plots to tables, and our table now looks like this:
```
[ Info: Bomex: Number of unique allocating sites: 40
┌───────────────────┬─────────────┬─────────────────────────────────────────────────────────────────────────┐
│     Allocations % │ Allocations │                                                    <file>:<line number> │
│ (alloc_i/∑allocs) │     (bytes) │                                                                         │
├───────────────────┼─────────────┼─────────────────────────────────────────────────────────────────────────┤
│                19 │     2844800 │                TurbulenceConvection.jl/driver/compute_diagnostics.jl:55 │
│                19 │     2749824 │ OrdinaryDiffEq/t0VTQ/src/perform_step/fixed_timestep_perform_step.jl:81 │
│                14 │     2122688 │                        ClimaCore/Z5Pub/src/DataLayouts/broadcast.jl:190 │
│                14 │     2021376 │                          TurbulenceConvection.jl/driver/NetCDFIO.jl:149 │
│                10 │     1485120 │             TurbulenceConvection.jl/src/Turbulence_PrognosticTKE.jl:243 │
│                10 │     1422160 │                            TurbulenceConvection.jl/driver/Surface.jl:64 │
│                 5 │      742560 │                              ClimaCore/Z5Pub/src/Fields/broadcast.jl:43 │
│                 2 │      305312 │            OrdinaryDiffEq/t0VTQ/src/integrators/integrator_utils.jl:323 │
│                 1 │      181152 │               TurbulenceConvection.jl/driver/compute_diagnostics.jl:160 │
│                 1 │      174720 │                      TurbulenceConvection.jl/src/EDMF_Environment.jl:94 │
│                 1 │      102240 │                                TurbulenceConvection.jl/src/Fields.jl:55 │
│                 1 │       90848 │               TurbulenceConvection.jl/driver/compute_diagnostics.jl:303 │
│                 0 │       65520 │                           TurbulenceConvection.jl/src/update_aux.jl:375 │
│                 0 │       58848 │                          TurbulenceConvection.jl/driver/NetCDFIO.jl:167 │
│                 0 │       43680 │             TurbulenceConvection.jl/src/Turbulence_PrognosticTKE.jl:572 │
│                 0 │       40320 │                          TurbulenceConvection.jl/driver/NetCDFIO.jl:144 │
│                 0 │       34944 │                              SciMLBase/jj8Ix/src/scimlfunctions.jl:1429 │
│                 0 │       22464 │                                ClimaCore/Z5Pub/src/Fields/Fields.jl:201 │
│                 0 │       21840 │                           TurbulenceConvection.jl/src/update_aux.jl:387 │
│                 0 │       16032 │             TurbulenceConvection.jl/src/Turbulence_PrognosticTKE.jl:856 │
│                 0 │       11184 │                          TerminalLoggers/Mks0N/src/StickyMessages.jl:53 │
│                 0 │       10688 │               TurbulenceConvection.jl/driver/compute_diagnostics.jl:197 │
│                 0 │        9648 │                                   OrdinaryDiffEq/t0VTQ/src/solve.jl:413 │
│                 0 │        9536 │                         SciMLBase/jj8Ix/src/problems/ode_problems.jl:76 │
│                 0 │        8016 │             TurbulenceConvection.jl/src/Turbulence_PrognosticTKE.jl:853 │
│                 0 │        7488 │                                   OrdinaryDiffEq/t0VTQ/src/solve.jl:280 │
│                 0 │        7440 │                         TerminalLoggers/Mks0N/src/TerminalLogger.jl:338 │
│                 0 │        7424 │            OrdinaryDiffEq/t0VTQ/src/integrators/integrator_utils.jl:103 │
│                 0 │        7168 │                        OrdinaryDiffEq/t0VTQ/src/integrators/type.jl:144 │
│                 0 │        6224 │                         TerminalLoggers/Mks0N/src/TerminalLogger.jl:125 │
│                 0 │        5376 │                          TurbulenceConvection.jl/driver/NetCDFIO.jl:180 │
│                 0 │        4848 │                              TurbulenceConvection.jl/driver/main.jl:100 │
│                 0 │        4720 │                             TurbulenceConvection.jl/src/variables.jl:37 │
│                 0 │        4320 │                  TurbulenceConvection.jl/src/TurbulenceConvection.jl:56 │
│                 0 │        3808 │                         TerminalLoggers/Mks0N/src/TerminalLogger.jl:262 │
│                 0 │        3584 │                          TerminalLoggers/Mks0N/src/StickyMessages.jl:60 │
│                 0 │        3360 │                         TerminalLoggers/Mks0N/src/TerminalLogger.jl:252 │
│                 0 │        3136 │                                     OrdinaryDiffEq/t0VTQ/src/solve.jl:6 │
│                 0 │        2992 │             TerminalLoggers/Mks0N/src/ProgressMeter/ProgressMeter.jl:87 │
│                 0 │        2976 │                         TerminalLoggers/Mks0N/src/StickyMessages.jl:100 │
└───────────────────┴─────────────┴─────────────────────────────────────────────────────────────────────────┘
```

**Comment by Alexander-Barth** [comment]
It is great to see that the setindex! allocation can also be avoided in your case now.
These changes are part of the 0.11.8 release.

**Comment by charleskawczynski** [comment]
Thank you, amazing! I think we can close this issue 🎉
