### ISSUE TITLE
Disentangle the EDMF and microphysics 

### ISSUE THREAD

**Issue by yairchn** [CliMA/TurbulenceConvection.jl#808]
Currently the coupling between EDMF microphysics and grid mean microphysics is hard coded in driver/dycore.jl:
https://github.com/CliMA/TurbulenceConvection.jl/blob/aeeba1b8bf10180e014aa401093617e811d8dc95/driver/dycore.jl#L329

At the same time, the microphysics model that is used by the SCM is defined inside the EDMF model:
https://github.com/CliMA/TurbulenceConvection.jl/blob/cf982f66d36664f47fdf9f841c92d4ce2e453b16/src/types.jl#L467

so that once an alternative to EDMF model is added we cannot call microphysics without the EDMF model.

I think we need to define the microphysics model in the Simulation1d function in driver/main.jl so that it is independent of EDMF and dispatch to either using the EDMF subdomains or not when updating microphysical sources.

**Comment by trontrytel** [comment]
Does it mean you want to support EDMF with and without microphysics and "alternative EDMF" with and without microphysics? I thought we agreed that in the interest of simplicity we will think of EDMF and microphysics as one inseparable thing

**Comment by trontrytel** [comment]
I think I would suggest first adding microphysics to one of the existing ClimaAtmos exampels. This way we would have an example of microphysics coupled to the grid mean. 

We can always switch off the sgs coupling to microphysics by running TC.jl with `precip_model = None`.

**Comment by yairchn** [comment]
first attempt of that would be #812
