### ISSUE TITLE
gradient of centre variables are defined at the center? 

### ISSUE THREAD

**Issue by yairchn** [CliMA/TurbulenceConvection.jl#823]
gradients of center variables such as `∇θ_liq_ice_gm ` are defined as `cent_aux_vars_gm` themselves, such as here:

https://github.com/CliMA/TurbulenceConvection.jl/blob/e10153f7c171ccc4fd657030fc0bcc33e2680d37/driver/dycore.jl#L61

**Comment by charleskawczynski** [comment]
This isn't really a problem, we basically compute upwind gradients (by taking gradients of upwind-biased interpolated fields), so it's a collocated operation.
