### ISSUE TITLE
Potential IO bug

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/TurbulenceConvection.jl#897]
I think we may have an IO bug: I think that (based on looking at the code), for a given `nsteps`, some variables have `nsteps` outputs while others have `nsteps+1`.

**Comment by charleskawczynski** [comment]
We should be able to confirm this easily by looping through each variable and checking the length of the time dimension.

**Comment by trontrytel** [comment]
I wonder if it's the same bug as this: https://github.com/CliMA/TurbulenceConvection.jl/issues/821

**Comment by charleskawczynski** [comment]
True, I think it's highly likely
