### ISSUE TITLE
Add thermo state fields

### ISSUE THREAD

**Issue by trontrytel** [CliMA/TurbulenceConvection.jl#944]
Add thermo state fields and isolate the if-else statements. This should help trim things down a bit for example with the equilibrium vs non-equilibrium moisture model. 

A demo is here: https://github.com/CliMA/TurbulenceConvection.jl/pull/937

**Comment by charleskawczynski** [comment]
I've added thermo state fields in #945, but they're not fully set and used yet.

**Comment by charleskawczynski** [comment]
Related PRs:
 - #945, #950, #947, #946,

**Comment by charleskawczynski** [comment]
Thermo fields have been added, closing in favor of #970, which is a bit more specific
