### ISSUE TITLE
change the grid mean thermodynamic variable to total energy

### ISSUE THREAD

**Issue by yairchn** [CliMA/TurbulenceConvection.jl#964]
This issue is tracks the change of thermodynamic variable in the grid mean from liquid ice potential temperature (`θ_liq_ice`) to density times total energy (`ρe_tot`). 
The change is involving several steps:

- [x] change of the EDMF SGS flux to total energy.  This is done now by locally computing the total enthalpy `h = e+p/ρ` of the subdomains and computing `ρ∑aᵢ(w̄ᵢ-⟨w⟩)(h̄ᵢ-⟨h⟩)` and the same for diffusive fluxes. 
- [x] change the large scale tendencies (radiation, subsidence, LES prescribed forcing and nudging etc.) to total energy  
- [x] change to the computation of surface fluxes, and their use in the updraft BCs.
- [ ] change to the tendencies from microphysics

Draft [PR906](https://github.com/CliMA/TurbulenceConvection.jl/pull/960) is under ongoing development, where several problems still persist.

===============================
Tests: run buildkite tests with all cases and compare the results for the current code.

**Comment by charleskawczynski** [comment]
@yairchn, can we close this?

**Comment by yairchn** [comment]
yes
